name: Terraform Apply for Main

on:
  workflow_call:
    inputs:
      account:
        description: 'The AWS account to deploy to (e.g., prod, sec)'
        required: true
        type: string
        
      aws_region:
        required: true
        type: string
        description: 'AWS Region'
        
      aws_role_to_assume:
        required: true
        type: string
        description: 'IAM Role ARN to assume via OIDC'
    secrets:
      snyk_token:
        description: 'Snyk API token for authentication'
        required: true
        
jobs:
  security-check:
    name: Snyk IaC Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk IaC Test
        run: snyk iac test . --report --severity-threshold=high

      - name: Show Snyk Test Results
        if: failure()
        run: echo "Snyk IaC tests failed. Please review security issues."

  terraform-apply:
    name: Terraform Apply for ${{ inputs.account }} Account
    runs-on: ubuntu-latest
    needs: security-check
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform/${{ inputs.account}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ inputs.aws_role_to_assume }}
          aws-region: ${{ inputs.aws_region }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7

      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Plan Terraform
        id: plan
        run: terraform plan -var-file=${{ inputs.account }}.tfvars
      
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Apply Terraform
        if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
        run: terraform apply -auto-approve -var-file=${{ inputs.account }}.tfvars
      # - name: Destroy Terraform
      #   run: terraform destroy -auto-approve -var-file=${{ inputs.account }}.tfvars
 
      - name: Post-Deployment Notifications
        run: echo "Deployment to ${{ inputs.account }} environment completed."

