name: Terraform Plan for Development

on:
  workflow_call:
    inputs:
      account:
        description: 'The AWS account to deploy to (e.g., prod, sec)'
        required: true
        type: string
        
      aws_region:
        required: true
        type: string
        description: 'AWS Region'
        
      aws_role_to_assume:
        required: true
        type: string
        description: 'IAM Role ARN to assume via OIDC'

jobs:
  terraform-apply:
    name: Terraform Apply for ${{ inputs.account }}
    runs-on: ubuntu-latest
    # needs: snyk-iac-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ inputs.aws_role_to_assume }}
          aws-region: ${{ inputs.aws_region }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        run: terraform init

      - name: Plan Terraform
        id: plan
        run: terraform plan -var-file= ${{ inputs.account }}.tfvars
      
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Post-Deployment Notifications
        run: echo "Deployment to ${{ inputs.account }} environment completed."

